### ISSUE TITLE
git commit hooks adding content to commits

### ISSUE THREAD

**Issue by simongottschlag** [mikaelvesavuori/slamax#3]
Hi @mikaelvesavuori!

It's hard to do "clean commits" using the commit hooks since they are adding everything that's changed. I usually prefer to add the changed code in one commit and then the generated content in another, keeping the commit history clear and consise.

Just close issue if you don't agree. :^)

**Comment by mikaelvesavuori** [comment]
I see your point, but not sure what the "ideal" way to -absolutely- ensure all content is generated etc would be. Do you trust people? I don't even trust myself! ^^

**Comment by simongottschlag** [comment]
@mikaelvesavuori I agree, but put these checks into the PR validation. I'll link an example how I've done it (with make, but you'll get the idea).

Edit:
link: https://github.com/XenitAB/terraform-modules/blob/main/.github/workflows/check.yaml

(writing from phone)
