### ISSUE TITLE
rounding of floats

### ISSUE THREAD

**Issue by simongottschlag** [mikaelvesavuori/slamax#4]
Hi @mikaelvesavuori!

When looking at the logic and trying to mimic it, I noticed that rounding is taking place at each iteration of the composite SLA instead of at the end, as well as it's actually not rounding but cutting (`99.956` becomes `99.95` and not `99.96`).

Since I'm no domain expert, this may be how it's done. Just wanted to check with you that it's intentional.

**Comment by mikaelvesavuori** [comment]
Hey!

Yes, that's a good catch. I'll set a single use of [`.toPrecision(5)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toPrecision) at the end instead, which I think should do the trick. I'll also correct you that both `.toFixed()` and `.toPrecision()` _will_ round numbers.

Tests don't show much meaningful difference (had to update a single digit in a test, so seems to work as expected). I'll check in the new revised logic now.

**Comment by simongottschlag** [comment]
You are most likely correct, noticed the issue when replicating the logic and noted that I was off by one in this test: https://github.com/mikaelvesavuori/slamax/blob/main/tests/takesCustomInputs.test.ts

**Comment by mikaelvesavuori** [comment]
That case should be taken care of, so closing. Thanks for feedback leading to a better product!
